from dataclasses import dataclass


@dataclass
class Dish:
    category: str
    name: str
    filename: str
    extra_query: str = ""


MENU = [
    Dish("Chinese Appetizers", "Chilli Paneer Dry", "chilli-paneer-dry.jpg"),
    Dish("Chinese Appetizers", "Chilli Baby Corn", "chilli-baby-corn.jpg"),
    Dish("Chinese Appetizers", "Paneer'65", "paneer-65.jpg"),
    Dish("Chinese Appetizers", "Crispy Corn Salt & Pepper", "crispy-corn-salt-pepper.jpg"),
    Dish("Chinese Appetizers", "American Corn", "american-corn.jpg"),
    Dish("Chinese Appetizers", "Chilli Mushroom", "chilli-mushroom.jpg"),
    Dish("Chinese Appetizers", "Chilli Soya Chaap", "chilli-soya-chaap.jpg"),
    Dish("Chinese Appetizers", "Spring Roll", "spring-roll.jpg"),
    Dish("Chinese Appetizers", "Honey Chilli Potato", "honey-chilli-potato.jpg"),
    Dish("Chinese Appetizers", "Chilli Potato", "chilli-potato.jpg"),
    Dish("Chinese Appetizers", "Paneer-in-Hot Garlic", "paneer-in-hot-garlic.jpg"),
    Dish("Chinese Appetizers", "Veg Manchurian Dry", "veg-manchurian-dry.jpg"),
    Dish("Chinese Appetizers", "Paneer Manchurian Dry", "paneer-manchurian-dry.jpg"),
    Dish("Chinese Appetizers", "Crispy Baby Corn", "crispy-baby-corn.jpg"),
    Dish("Chinese Appetizers", "Paneer Green Garlic", "paneer-green-garlic.jpg"),
    Dish("Chinese Appetizers", "Crispy Veggies (Salt & Pepper)", "crispy-veggies-salt-pepper.jpg"),

    Dish("Dumplings / Momos", "Steem Veg Momos", "steem-veg-momos.jpg"),
    Dish("Dumplings / Momos", "Steem Paneer Momos", "steem-paneer-momos.jpg"),
    Dish("Dumplings / Momos", "Veg Kurkure Momos", "veg-kurkure-momos.jpg"),
    Dish("Dumplings / Momos", "Paneer Kurkure Momos", "paneer-kurkure-momos.jpg"),
    Dish("Dumplings / Momos", "Pan Fried Chilli Garlic Momos", "pan-fried-chilli-garlic-momos.jpg"),
    Dish("Dumplings / Momos", "Tandoori Veg Momos", "tandoori-veg-momos.jpg"),
    Dish("Dumplings / Momos", "Tandoori Paneer Momos", "tandoori-paneer-momos.jpg"),

    Dish("Saucy Delights", "Manchurian Gravy", "manchurian-gravy.jpg"),
    Dish("Saucy Delights", "Chilli Paneer Gravy", "chilli-paneer-gravy.jpg"),
    Dish("Saucy Delights", "Veg Hot Garlic Gravy", "veg-hot-garlic-gravy.jpg"),
    Dish("Saucy Delights", "Chilli Mushroom Gravy", "chilli-mushroom-gravy.jpg"),

    Dish("Chinese Cuisine", "Veg Fried Rice", "veg-fried-rice.jpg"),
    Dish("Chinese Cuisine", "Schezwan Fried Rice", "schezwan-fried-rice.jpg"),
    Dish("Chinese Cuisine", "Chilli Garlic Fried Rice", "chilli-garlic-fried-rice.jpg"),
    Dish("Chinese Cuisine", "Veg Noodles", "veg-noodles.jpg"),
    Dish("Chinese Cuisine", "Hakka Noodles", "hakka-noodles.jpg"),
    Dish("Chinese Cuisine", "Singapori Noodles", "singapori-noodles.jpg"),
    Dish("Chinese Cuisine", "Chilli Garlic Noodles", "chilli-garlic-noodles.jpg"),
    Dish("Chinese Cuisine", "Schezwan Noodles", "schezwan-noodles.jpg"),
    Dish("Chinese Cuisine", "Paneer Noodles", "paneer-noodles.jpg"),

    Dish("Salads", "Garden green Salad", "garden-green-salad.jpg"),
    Dish("Salads", "Cucumber Salad", "cucumber-salad.jpg"),
    Dish("Salads", "Onion Salad", "onion-salad.jpg"),
    Dish("Salads", "Kimchi Salad", "kimchi-salad.jpg"),

    Dish("Indian Breads", "Plain Roti", "plain-roti.jpg"),
    Dish("Indian Breads", "Butter Roti", "butter-roti.jpg"),
    Dish("Indian Breads", "Laccha Paratha", "laccha-paratha.jpg"),
    Dish("Indian Breads", "Tava Roti Plain", "tava-roti-plain.jpg"),
    Dish("Indian Breads", "Tava Roti Butter", "tava-roti-butter.jpg"),
    Dish("Indian Breads", "Plain Naan", "plain-naan.jpg"),
    Dish("Indian Breads", "Butter Naan", "butter-naan.jpg"),
    Dish("Indian Breads", "Cheese Naan", "cheese-naan.jpg"),
    Dish("Indian Breads", "Garlic Naan", "garlic-naan.jpg"),
    Dish("Indian Breads", "Kashmiri Naan", "kashmiri-naan.jpg"),
    Dish("Indian Breads", "Missi Roti", "missi-roti.jpg"),
    Dish("Indian Breads", "Onion Missi Roti", "onion-missi-roti.jpg"),
    Dish("Indian Breads", "Stuffed Naan", "stuffed-naan.jpg"),
    Dish("Indian Breads", "Rumali Roti", "rumali-roti.jpg"),
    Dish("Indian Breads", "Bread Basket", "bread-basket.jpg"),

    Dish("Paratha's", "Paneer Paratha", "paneer-paratha.jpg"),
    Dish("Paratha's", "Aloo Paratha", "aloo-paratha.jpg"),
    Dish("Paratha's", "Onion Paratha", "onion-paratha.jpg"),
    Dish("Paratha's", "Mix Veg Paratha", "mix-veg-paratha.jpg"),
    Dish("Paratha's", "Green Chilli Paratha", "green-chilli-paratha.jpg"),
    Dish("Paratha's", "Gobhi Paratha", "gobhi-paratha.jpg"),

    Dish("Dal Delight", "Dal Makhani", "dal-makhani.jpg"),
    Dish("Dal Delight", "Dal Handi (Amritsari)", "dal-handi-amritsari.jpg"),
    Dish("Dal Delight", "Yellow Dal Tadka", "yellow-dal-tadka.jpg"),
    Dish("Dal Delight", "Dal Fry", "dal-fry.jpg"),
    Dish("Dal Delight", "Dal Panchrangi", "dal-panchrangi.jpg"),

    Dish("Rice", "Steam Rice", "steam-rice.jpg"),
    Dish("Rice", "Jeera Rice", "jeera-rice.jpg"),
    Dish("Rice", "Veg Pulao", "veg-pulao.jpg"),
    Dish("Rice", "Matar Pulao", "matar-pulao.jpg"),
    Dish("Rice", "Kashmiri Pulao", "kashmiri-pulao.jpg"),

    Dish("Biryani", "Veg Biryani", "veg-biryani.jpg"),
    Dish("Biryani", "Paneer Tikka Biryani", "paneer-tikka-biryani.jpg"),
    Dish("Biryani", "Veg Hyderabadi Biryani", "veg-hyderabadi-biryani.jpg"),

    Dish("Raitas", "Boondi Raita", "boondi-raita.jpg"),
    Dish("Raitas", "Mix Veg Raita", "mix-veg-raita.jpg"),
    Dish("Raitas", "Pineapple Raita", "pineapple-raita.jpg"),
    Dish("Raitas", "Fruit Raita", "fruit-raita.jpg"),
    Dish("Raitas", "Plain Curd", "plain-curd.jpg"),

    Dish("Indian Main Course", "Paneer Lababdar", "paneer-lababdar.jpg"),
    Dish("Indian Main Course", "Kadhai Paneer", "kadhai-paneer.jpg"),
    Dish("Indian Main Course", "Paneer Makhani", "paneer-makhani.jpg"),
    Dish("Indian Main Course", "Paneer Do Pyaza", "paneer-do-pyaza.jpg"),
    Dish("Indian Main Course", "Panner Butter Masala", "panner-butter-masala.jpg"),
    Dish("Indian Main Course", "Paneer Tikka Masala", "paneer-tikka-masala.jpg"),
    Dish("Indian Main Course", "Handi Paneer", "handi-paneer.jpg"),
    Dish("Indian Main Course", "Paneer Rogan Josh", "paneer-rogan-josh.jpg"),
    Dish("Indian Main Course", "Palak Paneer", "palak-paneer.jpg"),
    Dish("Indian Main Course", "Paneer Changezi", "paneer-changezi.jpg"),
    Dish("Indian Main Course", "Shahi Paneer", "shahi-paneer.jpg"),
    Dish("Indian Main Course", "Paneer Kali Mirch", "paneer-kali-mirch.jpg"),
    Dish("Indian Main Course", "Navratan Korma", "navratan-korma.jpg"),
    Dish("Indian Main Course", "Lucknowi Kofta", "lucknowi-kofta.jpg"),
    Dish("Indian Main Course", "Malai Kofta", "malai-kofta.jpg"),
    Dish("Indian Main Course", "Mutter Paneer", "mutter-paneer.jpg"),
    Dish("Indian Main Course", "Mushroom Masala Mutter", "mushroom-masala-mutter.jpg"),
    Dish("Indian Main Course", "Mushroom Do Pyaza", "mushroom-do-pyaza.jpg"),
    Dish("Indian Main Course", "Mushroom Masala", "mushroom-masala.jpg"),
    Dish("Indian Main Course", "Corn Palak", "corn-palak.jpg"),
    Dish("Indian Main Course", "Mix Veg", "mix-veg.jpg"),
    Dish("Indian Main Course", "Nizami Handi (Hyderabadi)", "nizami-handi-hyderabadi.jpg"),
    Dish("Indian Main Course", "Jeera Aloo", "jeera-aloo.jpg"),
    Dish("Indian Main Course", "Gobhi Adraki", "gobhi-adraki.jpg"),
    Dish("Indian Main Course", "Pindi Chana Masala", "pindi-chana-masala.jpg"),
    Dish("Indian Main Course", "Methi Mutter Malai", "methi-mutter-malai.jpg"),
    Dish("Indian Main Course", "Kadhai Mushroom", "kadhai-mushroom.jpg"),
    Dish("Indian Main Course", "Jalfrezi", "jalfrezi.jpg"),
    Dish("Indian Main Course", "Punjabi Aloo", "punjabi-aloo.jpg"),
    Dish("Indian Main Course", "Kadhai Soya Chaap", "kadhai-soya-chaap.jpg"),
    Dish("Indian Main Course", "Soya Chaap Tikka Masala", "soya-chaap-tikka-masala.jpg"),

    Dish("Warm & Cozy", "Tea (HOT)", "tea-hot.jpg"),
    Dish("Warm & Cozy", "Masala Tea (HOT)", "masala-tea-hot.jpg"),
    Dish("Warm & Cozy", "Coffee (HOT)", "coffee-hot.jpg"),
    Dish("Warm & Cozy", "Green Tea", "green-tea.jpg"),
    Dish("Warm & Cozy", "Lemon Tea", "lemon-tea.jpg"),
    Dish("Warm & Cozy", "Black Tea", "black-tea.jpg"),
    Dish("Warm & Cozy", "Black Coffee", "black-coffee.jpg"),

    Dish("Shake It Up!", "Cold Coffee", "cold-coffee.jpg"),
    Dish("Shake It Up!", "Cold Coffee (With ice cream)", "cold-coffee-with-ice-cream.jpg"),
    Dish("Shake It Up!", "Strawberry Shake", "strawberry-shake.jpg"),
    Dish("Shake It Up!", "Butter Scotch Shake", "butter-scotch-shake.jpg"),
    Dish("Shake It Up!", "Chocolate Shake", "chocolate-shake.jpg"),
    Dish("Shake It Up!", "Vanilla Shake", "vanilla-shake.jpg"),
    Dish("Shake It Up!", "Black Current Shake", "black-current-shake.jpg"),
    Dish("Shake It Up!", "Banana Shake", "banana-shake.jpg"),
    Dish("Shake It Up!", "Belgian Chocolate Shake", "belgian-chocolate-shake.jpg"),
    Dish("Shake It Up!", "Oreo Shake", "oreo-shake.jpg"),
    Dish("Shake It Up!", "Kit Kat Shake", "kit-kat-shake.jpg"),
    Dish("Shake It Up!", "Mango Shake", "mango-shake.jpg"),
    Dish("Shake It Up!", "Choco Cookies Shake", "choco-cookies-shake.jpg"),
    Dish("Shake It Up!", "Choco Nutella Shake", "choco-nutella-shake.jpg"),
    Dish("Shake It Up!", "Choco Brownie Shake", "choco-brownie-shake.jpg"),
    Dish("Shake It Up!", "Choco Muffin Shake", "choco-muffin-shake.jpg"),
    Dish("Shake It Up!", "Choco Fudge Shake", "choco-fudge-shake.jpg"),
    Dish("Shake It Up!", "Choco Hazelnut Shake", "choco-hazelnut-shake.jpg"),

    Dish("Fizzy Mocktails", "Blue Lagoon", "blue-lagoon.jpg"),
    Dish("Fizzy Mocktails", "Virgin Mojito", "virgin-mojito.jpg"),
    Dish("Fizzy Mocktails", "Orange Mojito", "orange-mojito.jpg"),
    Dish("Fizzy Mocktails", "Mint Mojito", "mint-mojito.jpg"),
    Dish("Fizzy Mocktails", "Fresh Lime Soda (Sweet/Salt/Mix)", "fresh-lime-soda.jpg"),
    Dish("Fizzy Mocktails", "Ice Tea", "ice-tea.jpg"),
    Dish("Fizzy Mocktails", "Fruit Punch", "fruit-punch.jpg"),
    Dish("Fizzy Mocktails", "Aam Panna", "aam-panna.jpg"),
    Dish("Fizzy Mocktails", "Mango Cooler", "mango-cooler.jpg"),

    Dish("Soulful Soups", "Manchow Soup", "manchow-soup.jpg"),
    Dish("Soulful Soups", "Hot & Sour Soup", "hot-sour-soup.jpg"),
    Dish("Soulful Soups", "Sweet Corn Soup", "sweet-corn-soup.jpg"),
    Dish("Soulful Soups", "Lemon Coriander Soup", "lemon-coriander-soup.jpg"),
    Dish("Soulful Soups", "Cream Of Tomato Soup", "cream-of-tomato-soup.jpg"),
    Dish("Soulful Soups", "Cream Of Mushroom Soup", "cream-of-mushroom-soup.jpg"),
    Dish("Soulful Soups", "Veg Clear Soup", "veg-clear-soup.jpg"),
    Dish("Soulful Soups", "Thupka Soup", "thupka-soup.jpg"),

    Dish("Lassi", "Butter Milk (Masala Chhas)", "butter-milk-masala-chhas.jpg"),
    Dish("Lassi", "Punjabi Lassi (Sweet)", "punjabi-lassi-sweet.jpg"),

    Dish("Tandoori Station", "Tandoori Paneer Tikka", "tandoori-paneer-tikka.jpg"),
    Dish("Tandoori Station", "Tandoori Paneer Malai Tikka", "tandoori-paneer-malai-tikka.jpg"),
    Dish("Tandoori Station", "Tandoori Achari Paneer Tikka", "tandoori-achari-paneer-tikka.jpg"),
    Dish("Tandoori Station", "Tandoori Pudina Paneer Tikka", "tandoori-pudina-paneer-tikka.jpg"),
    Dish("Tandoori Station", "Tandoori Pudina Soya Chaap", "tandoori-pudina-soya-chaap.jpg"),
    Dish("Tandoori Station", "Tandoori Masala Chaap", "tandoori-masala-chaap.jpg"),
    Dish("Tandoori Station", "Tandoori Stuffed Aloo", "tandoori-stuffed-aloo.jpg"),
    Dish("Tandoori Station", "Afghani Soya Chaap", "afghani-soya-chaap.jpg"),
    Dish("Tandoori Station", "Tandoori Soya Chaap", "tandoori-soya-chaap.jpg"),
    Dish("Tandoori Station", "Tandoori Malai Chaap", "tandoori-malai-chaap.jpg"),
    Dish("Tandoori Station", "Tandoori Achari Chaap", "tandoori-achari-chaap.jpg"),
    Dish("Tandoori Station", "Tandoori Mushroom Tikka", "tandoori-mushroom-tikka.jpg"),
    Dish("Tandoori Station", "Tandoori Stuffed Mushroom Tikka", "tandoori-stuffed-mushroom-tikka.jpg"),
    Dish("Tandoori Station", "Tandoori Broccoli", "tandoori-broccoli.jpg"),
    Dish("Tandoori Station", "Tandoori Veg Seekh Kabab", "tandoori-veg-seekh-kabab.jpg"),
    Dish("Tandoori Station", "Dahi Ke Kabab", "dahi-ke-kabab.jpg"),
    Dish("Tandoori Station", "Hara Bhara Kabab", "hara-bhara-kabab.jpg"),
    Dish("Tandoori Station", "Tandoori Pineapple Tikka", "tandoori-pineapple-tikka.jpg"),
    Dish("Tandoori Station", "Dahi Ke Shole", "dahi-ke-shole.jpg"),
    Dish("Tandoori Station", "Chilli Paneer Roll", "chilli-paneer-roll.jpg"),
    Dish("Tandoori Station", "Paneer Tikka Roll", "paneer-tikka-roll.jpg"),
    Dish("Tandoori Station", "Malai Paneer Tikka Roll", "malai-paneer-tikka-roll.jpg"),
    Dish("Tandoori Station", "Tandoori Chaap Roll", "tandoori-chaap-roll.jpg"),
]
